// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cost struct {
	CostID      string
	ProjectID   string
	CostType    string
	Description string
	Comment     pgtype.Text
	Amount      float64
	Currency    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Installment struct {
	InstallmentID string
	CostID        string
	PaymentDate   pgtype.Date
	Amount        float64
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Project struct {
	ProjectID   string
	Description string
	StartDate   pgtype.Date
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
